Import Libraries

In [3]:
import pandas as pd
import numpy as np

Reading Dataset

In [4]:
data = pd.read_csv('/content/Student_Performance_Factors (raw_data).csv')
data.head()

,Student_id,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,...,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,1001,23,84,Low,High,No,7,73,Low,Yes,...,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,1002,19,64,Low,Medium,No,8,59,Low,Yes,...,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,1003,24,98,Medium,Medium,Yes,7,91,Medium,Yes,...,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,1004,29,89,Low,Medium,Yes,8,98,Medium,Yes,...,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,1005,19,92,Medium,Medium,Yes,6,65,Medium,Yes,...,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [5]:
df = data.copy()

Check for Null Values

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_id                  6607 non-null   int64
 1   Hours_Studied               6607 non-null   int64
 2   Attendance                  6607 non-null   int64
 3   Parental_Involvement        6607 non-null   object
 4   Access_to_Resources         6607 non-null   object
 5   Extracurricular_Activities  6607 non-null   object
 6   Sleep_Hours                 6607 non-null   int64
 7   Previous_Scores             6607 non-null   int64
 8   Motivation_Level            6607 non-null   object
 9   Internet_Access             6607 non-null   object
 10  Tutoring_Sessions           6607 non-null   int64
 11  Family_Income               6607 non-null   object
 12  Teacher_Quality             6529 non-null   object
 13  School_Type                 6607 non-null   object
 14  Peer_Influence              6607 non-null   object
 15  Physical_Activity           6607 non-null   int64
 16  Learning_Disabilities       6607 non-null   object
 17  Parental_Education_Level    6517 non-null   object
 18  Distance_from_Home          6540 non-null   object
 19  Gender                      6607 non-null   object
 20  Exam_Score                  6607 non-null   int64
dtypes: int64(8), object(13)
memory usage: 1.1+ MB

Rearranging the columns

In [7]:
data.columns.values

array(['Student_id', 'Hours_Studied', 'Attendance',
       'Parental_Involvement', 'Access_to_Resources',
       'Extracurricular_Activities', 'Sleep_Hours', 'Previous_Scores',
       'Motivation_Level', 'Internet_Access', 'Tutoring_Sessions',
       'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'], dtype=object)

In [8]:
col_names = [
    'Student_id',
    'Gender',
    'School_Type',
    'Parental_Involvement',
    'Parental_Education_Level',
    'Motivation_Level',
    'Teacher_Quality',
    'Peer_Influence',
    'Distance_from_Home',
    'Internet_Access',
    'Access_to_Resources',
    'Extracurricular_Activities',
    'Learning_Disabilities',
    'Family_Income',
    'Hours_Studied',
    'Attendance',
    'Sleep_Hours',
    'Physical_Activity',
    'Previous_Scores',
    'Tutoring_Sessions',
    'Exam_Score'
]

df = df[col_names]
df.head()

,Student_id,Gender,School_Type,Parental_Involvement,Parental_Education_Level,Motivation_Level,Teacher_Quality,Peer_Influence,Distance_from_Home,Internet_Access,...,Extracurricular_Activities,Learning_Disabilities,Family_Income,Hours_Studied,Attendance,Sleep_Hours,Physical_Activity,Previous_Scores,Tutoring_Sessions,Exam_Score
0,1001,Male,Public,Low,High School,Low,Medium,Positive,Near,Yes,...,No,No,Low,23,84,7,3,73,0,67
1,1002,Female,Public,Low,College,Low,Medium,Negative,Moderate,Yes,...,No,No,Medium,19,64,8,4,59,2,61
2,1003,Male,Public,Medium,Postgraduate,Medium,Medium,Neutral,Near,Yes,...,Yes,No,Medium,24,98,7,4,91,2,74
3,1004,Male,Public,Low,High School,Medium,Medium,Negative,Moderate,Yes,...,Yes,No,Medium,29,89,8,4,98,1,71
4,1005,Female,Public,Medium,College,Medium,High,Neutral,Near,Yes,...,Yes,No,Medium,19,92,6,4,65,3,70

Check duplicates

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
# Remove duplicates
df = df.drop_duplicates()

# Confirm
df.duplicated().sum()

np.int64(0)

Handling Missing Values

*Exam_Score*

In [11]:
df['Exam_Score'].isnull().sum()

np.int64(0)

In [12]:
df = df.dropna(subset=['Exam_Score'])

*Attendance*

In [13]:
df['Attendance'].isnull().sum()

np.int64(0)

In [14]:
df = df.dropna(subset=['Attendance'])

*Hours_Studied*

In [15]:
df['Hours_Studied'].isnull().sum()

np.int64(0)

In [16]:
df = df.dropna(subset=['Hours_Studied'])

*Previous_Scores*

In [17]:
df['Previous_Scores'].isnull().sum()

np.int64(0)

In [18]:
median_prev_score = df['Previous_Scores'].median()
df['Previous_Scores'] = df['Previous_Scores'].fillna(median_prev_score)

*Motivation_Level*

In [19]:
df['Motivation_Level'].isnull().sum()

np.int64(0)

In [20]:
df['Motivation_Level'] = df['Motivation_Level'].fillna("Unknown")

*Tutoring_Sessions*

In [21]:
df['Tutoring_Sessions'].isnull().sum()

np.int64(0)

In [22]:
df['Tutoring_Sessions'] = df['Tutoring_Sessions'].fillna(0)

*CREATE ENGINEERED COLUMN – Performance_Level*

In [23]:
def performance_level(score):
    if score >= 75:
        return "Top Performer"
    elif score >= 50:
        return "Average Performer"
    else:
        return "Weak Performer"

df['Performance_Level'] = df['Exam_Score'].apply(performance_level)

In [24]:
df['Score_per_Hour'] = df['Exam_Score'] / df['Hours_Studied']

In [25]:
df[
    ['Exam_Score', 'Attendance', 'Hours_Studied',
     'Previous_Scores', 'Motivation_Level',
     'Tutoring_Sessions', 'Performance_Level']
].isnull().sum()

Exam_Score           0
Attendance           0
Hours_Studied        0
Previous_Scores      0
Motivation_Level     0
Tutoring_Sessions    0
Performance_Level    0
dtype: int64

In [26]:
df.head()

,Student_id,Gender,School_Type,Parental_Involvement,Parental_Education_Level,Motivation_Level,Teacher_Quality,Peer_Influence,Distance_from_Home,Internet_Access,...,Family_Income,Hours_Studied,Attendance,Sleep_Hours,Physical_Activity,Previous_Scores,Tutoring_Sessions,Exam_Score,Performance_Level,Score_per_Hour
0,1001,Male,Public,Low,High School,Low,Medium,Positive,Near,Yes,...,Low,23,84,7,3,73,0,67,Average Performer,2.913043
1,1002,Female,Public,Low,College,Low,Medium,Negative,Moderate,Yes,...,Medium,19,64,8,4,59,2,61,Average Performer,3.210526
2,1003,Male,Public,Medium,Postgraduate,Medium,Medium,Neutral,Near,Yes,...,Medium,24,98,7,4,91,2,74,Average Performer,3.083333
3,1004,Male,Public,Low,High School,Medium,Medium,Negative,Moderate,Yes,...,Medium,29,89,8,4,98,1,71,Average Performer,2.448276
4,1005,Female,Public,Medium,College,Medium,High,Neutral,Near,Yes,...,Medium,19,92,6,4,65,3,70,Average Performer,3.684211

# Clean Data Checkpoint

In [27]:
clean_df = df.copy()
clean_df.head()

,Student_id,Gender,School_Type,Parental_Involvement,Parental_Education_Level,Motivation_Level,Teacher_Quality,Peer_Influence,Distance_from_Home,Internet_Access,...,Family_Income,Hours_Studied,Attendance,Sleep_Hours,Physical_Activity,Previous_Scores,Tutoring_Sessions,Exam_Score,Performance_Level,Score_per_Hour
0,1001,Male,Public,Low,High School,Low,Medium,Positive,Near,Yes,...,Low,23,84,7,3,73,0,67,Average Performer,2.913043
1,1002,Female,Public,Low,College,Low,Medium,Negative,Moderate,Yes,...,Medium,19,64,8,4,59,2,61,Average Performer,3.210526
2,1003,Male,Public,Medium,Postgraduate,Medium,Medium,Neutral,Near,Yes,...,Medium,24,98,7,4,91,2,74,Average Performer,3.083333
3,1004,Male,Public,Low,High School,Medium,Medium,Negative,Moderate,Yes,...,Medium,29,89,8,4,98,1,71,Average Performer,2.448276
4,1005,Female,Public,Medium,College,Medium,High,Neutral,Near,Yes,...,Medium,19,92,6,4,65,3,70,Average Performer,3.684211

In [28]:
clean_df.to_excel('stud_perf_factor_clean_data.xlsx', index=False)
clean_df.to_csv('stud_perf_factor_clean_data.csv', index=False)

In [29]:
df['Parental_Education_Level'].isnull().sum()

np.int64(90)

In [30]:
df['Parental_Education_Level'].unique()

array(['High School', 'College', 'Postgraduate', nan], dtype=object)

In [31]:
df.columns.values

array(['Student_id', 'Gender', 'School_Type', 'Parental_Involvement',
       'Parental_Education_Level', 'Motivation_Level', 'Teacher_Quality',
       'Peer_Influence', 'Distance_from_Home', 'Internet_Access',
       'Access_to_Resources', 'Extracurricular_Activities',
       'Learning_Disabilities', 'Family_Income', 'Hours_Studied',
       'Attendance', 'Sleep_Hours', 'Physical_Activity',
       'Previous_Scores', 'Tutoring_Sessions', 'Exam_Score',
       'Performance_Level', 'Score_per_Hour'], dtype=object)